// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Data;

#nullable disable

namespace Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Migrations
{
    [DbContext(typeof(Padilla_Gabriel_Laboratorio_CodeFirst_2023_20Context))]
    partial class Padilla_Gabriel_Laboratorio_CodeFirst_2023_20ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.EstudianteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EstudianteModel");
                });

            modelBuilder.Entity("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.RecintoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecintoModel");
                });

            modelBuilder.Entity("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.Registro_VacModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVacunacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecintoId")
                        .HasColumnType("int");

                    b.Property<int>("VacunaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("RecintoId");

                    b.HasIndex("VacunaId");

                    b.ToTable("Registro_VacModel");
                });

            modelBuilder.Entity("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.VacunaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VacunaModel");
                });

            modelBuilder.Entity("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.Registro_VacModel", b =>
                {
                    b.HasOne("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.EstudianteModel", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.RecintoModel", "Recinto")
                        .WithMany()
                        .HasForeignKey("RecintoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padilla_Gabriel_Laboratorio_CodeFirst_2023_20.Models.VacunaModel", "Vacuna")
                        .WithMany()
                        .HasForeignKey("VacunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Recinto");

                    b.Navigation("Vacuna");
                });
#pragma warning restore 612, 618
        }
    }
}
